Add option to write to a file during solve
mumax/plus pull request #55
Opened 2024-12-10 15:31 UTC by ilateur

Pretty self-explanatory.
Should there also be an option for extremely large simulations to only write to a table, without keeping data in a dictionary in RAM?

2024-12-14 10:32 UTC, lamoreel requested changes
An option to avoid storing all data in RAM might be useful, but I would keep this very optional in order to keep the option to manipulate output in the same input file. Is a new function which only writes necessary? Or might `solve` just have another optional argument?

2024-12-14 10:32 UTC, lamoreel commented on mumaxplus/timesolver.py
> +            _os.makedirs(_os.path.dirname(self._file_name), exist_ok=True)
Only works if `self._file_name` contains a directory path, so giving only a file name raises a `FileNotFoundError`.

2024-12-14 21:19 UTC, ilateur commented on mumaxplus/timesolver.py
> +            _os.makedirs(_os.path.dirname(self._file_name), exist_ok=True)
Silly

2025-01-20 16:03 UTC, ilateur commented
I suggest we add that option later, but merge this feature like it is now

2025-01-20 16:20 UTC, lamoreel commented
If it works now, then yes.

2025-01-21 09:39 UTC, merged